$:
  vscode:
    - docker:
        image: docker.cnb.cool/sre/custom-vscode/node-18:latest
        #image: cnbcool/default-dev-env:latest
      runner:
        cpus: 8
      services:
        - vscode
        - docker
      stages:
        - name: cat /etc/os-release
          script: cat /etc/os-release

node-20:
  vscode:
    - docker:
        image: docker.cnb.cool/sre/custom-vscode/node-20:latest
        #image: cnbcool/default-dev-env:latest
      runner:
        cpus: 8
      services:
        - vscode
        - docker
      stages:
        - name: cat /etc/os-release
          script: cat /etc/os-release